export const DEMO_TOKEN = 'demo-mode'

const DEMO_EMAIL = 'demo@qinjian.local'

export const demoFixture = {
  me: {
    id: '11111111-1111-4111-8111-111111111111',
    email: DEMO_EMAIL,
    nickname: '陈一',
    ai_assist_enabled: true,
    privacy_mode: 'cloud',
    preferred_entry: 'daily',
    preferred_language: 'zh',
    tone_preference: 'gentle',
    response_length: 'medium',
    relationship_space_theme: 'classic',
    living_region: '上海',
    created_at: '2026-02-02T09:00:00',
  },
  currentPairId: '22222222-2222-4222-8222-222222222222',
  pairs: [
    {
      id: '22222222-2222-4222-8222-222222222222',
      user_a_id: '11111111-1111-4111-8111-111111111111',
      user_b_id: '33333333-3333-4333-8333-333333333333',
      type: 'couple',
      status: 'active',
      invite_code: 'A3H7K8M9Q2',
      partner_nickname: '林夏',
      partner_email: 'linxia@demo.local',
      custom_partner_nickname: '林夏',
      created_at: '2026-02-14T20:00:00',
    },
    {
      id: '77777777-7777-4777-8777-777777777777',
      user_a_id: '11111111-1111-4111-8111-111111111111',
      user_b_id: '88888888-8888-4888-8888-888888888888',
      type: 'friend',
      status: 'active',
      invite_code: 'B4J8L9N2P3',
      partner_nickname: '周宁',
      partner_email: 'zhouning@demo.local',
      custom_partner_nickname: '周宁',
      latest_change_request: {
        id: '77770000-7777-4777-8777-777777777777',
        pair_id: '77777777-7777-4777-8777-777777777777',
        kind: 'break_request',
        kind_label: '移除关系',
        status: 'rejected',
        status_label: '已恢复',
        requester_user_id: '11111111-1111-4111-8111-111111111111',
        requester_nickname: '陈一',
        approver_user_id: '88888888-8888-4888-8888-888888888888',
        approver_nickname: '周宁',
        requested_by_me: true,
        waiting_for_me: false,
        allow_retention: true,
        phase: 'retaining',
        expires_at: '2026-04-22T21:30:00',
        resolution_reason: 'retention_accepted',
        messages: [
          {
            id: '77771111-7777-4777-8777-777777777777',
            sender_user_id: '88888888-8888-4888-8888-888888888888',
            sender_nickname: '周宁',
            message: '我不想就这样结束，我们先把最近卡住的地方说清楚。',
            created_at: '2026-04-22T09:45:00',
          },
          {
            id: '77772222-7777-4777-8777-777777777777',
            sender_user_id: '88888888-8888-4888-8888-888888888888',
            sender_nickname: '周宁',
            message: '如果你愿意，我会先把之前答应的事补上。',
            created_at: '2026-04-22T11:20:00',
          },
        ],
        created_at: '2026-04-22T09:30:00',
        decided_at: '2026-04-22T12:10:00',
      },
      created_at: '2026-03-08T18:20:00',
    },
    {
      id: '99999999-9999-4999-8999-999999999999',
      user_a_id: '11111111-1111-4111-8111-111111111111',
      user_b_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
      type: 'friend',
      status: 'active',
      invite_code: 'C5K9M2Q4R7',
      partner_nickname: '顾遥',
      partner_email: 'guyao@demo.local',
      custom_partner_nickname: '顾遥',
      pending_change_request: {
        id: '99990000-9999-4999-8999-999999999999',
        pair_id: '99999999-9999-4999-8999-999999999999',
        kind: 'break_request',
        kind_label: '移除关系',
        status: 'pending',
        status_label: '待对方决定',
        requester_user_id: '11111111-1111-4111-8111-111111111111',
        requester_nickname: '陈一',
        approver_user_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
        approver_nickname: '顾遥',
        requested_by_me: true,
        waiting_for_me: false,
        allow_retention: true,
        phase: 'awaiting_retention_choice',
        expires_at: '2026-04-24T10:00:00',
        resolution_reason: null,
        messages: [],
        created_at: '2026-04-23T10:00:00',
        decided_at: null,
      },
      created_at: '2026-03-16T15:00:00',
    },
  ],
  notifications: [
    {
      id: '44444444-4444-4444-8444-444444444444',
      type: 'system',
      content: '林夏补了一条记录，今晚适合看一眼简报。',
      is_read: false,
      created_at: '2026-03-21T09:30:00',
    },
    {
      id: '55555555-5555-4555-8555-555555555555',
      type: 'pair_change',
      content: '顾遥这段关系里有一条移除关系申请，正在等对方决定是否挽留。',
      target_path: '/relationship-space/99999999-9999-4999-8999-999999999999',
      is_read: true,
      created_at: '2026-04-23T10:05:00',
    },
  ],
  todayStatus: {
    pair_id: '22222222-2222-4222-8222-222222222222',
    my_done: true,
    partner_done: true,
    both_done: true,
    has_report: true,
  },
  tree: {
    name: '关系树',
    level: 'tree',
    level_name: '话说开了',
    stage_label: '话说开了',
    stage_title: '原来别着的话，开始能说出来了',
      stage_explanation: '你们最近没那么僵着了，有些以前说不出口的话，现在也能聊开一些。',
    growth_points: 148,
    progress_percent: 57,
    next_level_at: 260,
    last_watered: '2026-04-12',
    can_water: true,
    water_bonus: 18,
    decay_per_day: 7,
    decay_grace_days: 0,
    energy_bubbles: [
      { label: '记录', value: '+12' },
      { label: '共情', value: '+8' },
      { label: '缓和', value: '+16' },
    ],
    energy_nodes: [
      { key: 'my_record', label: '记录', points: 10, state: 'available', collected: false, available: true, hint: '点击抓取成长值' },
      { key: 'partner_record', label: '同步', points: 8, state: 'available', collected: false, available: true, hint: '点击抓取成长值' },
      { key: 'small_repair', label: '小行动', points: 12, state: 'available', collected: false, available: true, hint: '点击抓取成长值' },
    ],
    leaves: [
      { label: '原话', value: '12 条', note: '这周被完整留下来的关键句' },
      { label: '缓和', value: '5 次', note: '从冷下来到重新接上的节点' },
      { label: '共同记忆', value: '18 个', note: '不是问题，也被保存下来的片段' },
    ],
  },
  relationshipSpaces: [
    {
      id: 'couple-repair',
      pair_id: '22222222-2222-4222-8222-222222222222',
      type: '情侣',
      title: '陈一和林夏',
      people: ['陈一', '林夏'],
      tree_stage: '小树',
      status: '今天适合低压力缓和',
      prompt: '先把“你没懂我”这句话留住，再约一个 10 分钟电话。',
      signal: 78,
      moments: ['昨天因为回复慢误会', '今天双方都愿意补一句解释', '下一步只确认一个小调整'],
    },
    {
      id: 'friend-sync',
      pair_id: '77777777-7777-4777-8777-777777777777',
      type: '朋友',
      title: '陈一和周宁',
      people: ['陈一', '周宁'],
      tree_stage: '新芽',
      status: '友情里需要同步期待',
      prompt: '适合说清楚“我不是不想见你，只是最近恢复很慢”。',
      signal: 84,
      moments: ['两周没约上饭', '一方担心被疏远', '可以用轻一点的方式重新约时间'],
    },
    {
      id: 'friend-boundary',
      pair_id: '99999999-9999-4999-8999-999999999999',
      type: '朋友',
      title: '陈一和顾遥',
      people: ['陈一', '顾遥'],
      tree_stage: '种子',
      status: '新关系先从低压力陪伴开始',
      prompt: '先约一件轻松的小事，不急着把关系定义得太满。',
      signal: 69,
      moments: ['刚开始一起玩', '双方还在找舒服的节奏', '适合保留一个小约定'],
    },
  ],
  relationshipMetrics: {
    '22222222-2222-4222-8222-222222222222': {
      score: 78,
      trend: 'up',
      summary: '今天双方都愿意补一句解释，关系在回暖。',
      nextAction: '先约一个 10 分钟电话，把误会说清楚。',
    },
    '77777777-7777-4777-8777-777777777777': {
      score: 84,
      trend: 'flat',
      summary: '友情整体稳定，但最近见面频率下降了一点。',
      nextAction: '发一个轻松邀约，先把见面重新约起来。',
    },
    '99999999-9999-4999-8999-999999999999': {
      score: 69,
      trend: 'up',
      summary: '这段新关系正在建立节奏，最近相处顺了一点。',
      nextAction: '先保留一个小约定，不急着定义关系。',
    },
  },
  crisis: {
    crisis_level: 'moderate',
    health_score: 78,
    intervention: {
      title: '先降温，再做个简单的缓和动作。',
      description: '先降温，今晚只说一个最重要的点。',
    },
  },
  communityTips: [
    {
      id: 'tip-demo-1',
      title: '先软一点开口',
      description: '如果最近容易顶起来，明天先换一个更柔和的开场。',
      content: '如果最近容易顶起来，明天先换一个更柔和的开场。',
    },
    {
      id: 'tip-demo-2',
      title: '留十分钟深聊',
      description: '如果最近总是浅聊，明天先约一个短一点的深聊窗口。',
      content: '如果最近总是浅聊，明天先约一个短一点的深聊窗口。',
    },
  ],
  tasks: {
    daily_note: '今天先做轻一点的三步，先把局面慢下来。',
    daily_pack_label: '今天先轻一点',
    adaptive_strategy: {
    reason: '先稳住情绪，再安排一个小行动。',
      copy_mode: 'gentle',
      copy_feedback_count: 3,
    },
    tasks: [
      {
        id: 'task-demo-1',
        title: '先停 10 分钟',
        description: '先别继续顶上去，给彼此 10 分钟缓一缓。',
        category: 'connection',
        source: 'system',
        is_manual: false,
        target_scope: 'both',
        status: 'pending',
      },
      {
        id: 'task-demo-2',
        title: '只讲一个点',
        description: '只说这次最卡的一件事，不顺手带第二件。',
        category: 'repair',
        source: 'system',
        is_manual: false,
        target_scope: 'both',
        status: 'pending',
      },
      {
        id: 'task-demo-3',
        title: '记下下次怎么更早停',
        description: '做完后留一句，下次出现同样情况时怎么更早刹车。',
        category: 'reflection',
        source: 'system',
        is_manual: false,
        target_scope: 'both',
        status: 'completed',
        feedback: {
          usefulness_score: 4,
          friction_score: 2,
          relationship_shift_score: 1,
          note: '这样做之后，对方没有继续把情绪顶高。',
        },
        needs_feedback: false,
      },
      {
        id: 'task-demo-4',
        title: '今晚打个短电话',
        description: '目标是确认彼此还在同一频道，而不是立刻讨论所有问题。',
        category: 'connection',
        source: 'manual',
        is_manual: true,
        target_scope: 'self',
        status: 'pending',
      },
    ],
  },
  streak: { streak: 6 },
  latestReport: {
    id: '66666666-6666-4666-8666-666666666666',
    pair_id: '22222222-2222-4222-8222-222222222222',
    report_type: 'daily',
    status: 'completed',
    created_at: '2026-03-21T22:10:00',
    health_score: 78,
    summary: '你们不是没有连接，只是每次想靠近时，容易先被压力打断。',
    key_insights: [
      '这周双方都没有完全退出关系，仍愿意继续回应。',
      '共同愿景和长期目标感仍然稳定。',
      '高压力表达仍会触发对方的防御。',
    ],
    recommendations: [
      '今天做一个简单的缓和动作，不求一次解决所有问题。',
      '用"我刚刚有点失落，因为……"代替"你怎么又……"。',
      '把复盘控制在10分钟内，只确认一个今晚能做到的小调整。',
    ],
  },
  narrativeAlignment: {
    event_id: '99999999-9999-4999-8999-999999999999',
    pair_id: '22222222-2222-4222-8222-222222222222',
    checkin_date: '2026-03-21',
    user_a_label: '陈一',
    user_b_label: '林夏',
    alignment_score: 71,
    shared_story: '你们都在乎这段关系，只是最近一个人在努力确认“我还重要吗”，另一个人在努力证明“我不是不在乎，只是太累了”。',
    view_a_summary: '你更在意被及时回应，因为延迟会被你接成自己不被在乎。',
    view_b_summary: '对方更像是在疲惫和压力里撤退，并不是真的想退出关系。',
    misread_risk: '最容易错位的点是：你的追问在对方那里会先被听成压力，而不是需要靠近。',
    divergence_points: ['你以为自己是在确认连接，对方感受到的是再次被要求交代。', '对方以为沉默是在避免升级，你感受到的却是被抛下。'],
    bridge_actions: ['先用一句低刺激感受表达开头，不要直接追问。', '先确认对方是否有 10 分钟空档，再进入主题。', '只对齐一个误解点，不要顺手扩展到所有旧问题。'],
  suggested_opening: '我不是想和你算账，我只是想把刚刚那点失落说清楚，试着找到一个更不累的沟通方式。',
    coach_note: '这次先对齐“彼此其实都没想退出”这一点，会比直接争谁更委屈更有帮助。',
    algorithm_version: 'relationship_judgement_v2',
    confidence: 0.74,
    decision_trace: { algorithm_version: 'relationship_judgement_v2', layer: 'alignment' },
    focus_labels: ['回应节奏', '缓冲空间'],
    risk_score: 0.29,
    baseline_delta: 17,
    fallback_reason: null,
    shadow_result: null,
    feedback_status: 'pending_feedback',
    reaction_shift: '林夏：这次更像在退开或关掉沟通。',
    deviation_reasons: ['陈一这次说得比平时更长，容易让对方先感到压力。', '林夏这次更像在退开，可能不是不在乎，而是需要先降温。'],
    history_sufficiency: 'limited',
    current_risk_level: 'moderate',
    active_plan_type: 'conflict_repair_plan',
    generated_at: '2026-03-21T22:15:00',
  },
    messageSimulation: {
    event_id: '88888888-8888-4888-8888-888888888888',
    draft: '你今天怎么又这么晚才回我，我真的很烦。',
    partner_view: '对方很可能先听成“你又做错了”，而不是“我现在有点受伤”。',
    likely_impact: '如果直接发送，接下来更可能进入解释、防御或沉默，而不是缓和。',
    risk_level: 'high',
    risk_reason: '这句话把情绪和指责绑在一起，对方更容易先感到压力，而不是看见你的真实需求。',
    safer_rewrite: '我刚刚有点失落，因为等了很久都没收到你的消息。你忙的时候如果能先告诉我一声，我会安心很多。',
    suggested_tone: '低刺激',
    conversation_goal: '先让对方听懂你的感受',
    do_list: ['先说自己的感受，再说一个具体需求。', '一次只说一个点，不要顺手翻旧账。', '把目标放在重新建立沟通窗口，而不是马上讲赢。'],
    avoid_list: ['避免“你怎么又”这类绝对化开头。', '不要把等待感直接写成指责。', '不要在情绪顶点继续加长句。'],
    algorithm_version: 'relationship_judgement_v2',
    confidence: 0.78,
    decision_trace: { algorithm_version: 'relationship_judgement_v2', layer: 'message_simulation' },
    focus_labels: ['回应节奏', '压力感'],
    risk_score: 2.3,
    baseline_delta: 1.3,
    fallback_reason: null,
    shadow_result: null,
    feedback_status: 'pending_feedback',
    baseline_match: 'strong_deviation',
    deviation_score: 0.78,
    deviation_reasons: ['本次语气更强烈，和平时表达习惯不同', '这次风险和刺激性明显高于平时'],
    reaction_shift: '这次更像在防御或顶回去。',
    evidence_summary: ['最近已有 2 次高风险发前检查。', '当前仍处在中度风险区间。', '当前建议先把表达放轻。'],
      limitation_note: '仅供发前参考。',
      safety_handoff: '如果已经多次变激烈，先别发。',
    },
    attachmentAnalysis: {
      scope: 'pair',
      analyzed_at: '2026-03-20T20:30:00',
      my_attachment: {
        type: 'anxious',
        label: '焦虑型',
        confidence: 0.81,
        analysis: '更在意回应速度，安静下来时容易先往坏处想。',
        growth_suggestion: '先把担心说成请求，不急着追问结论。',
      },
      partner_attachment: {
        type: 'avoidant',
        label: '回避型',
        confidence: 0.72,
        analysis: '压力上来时更容易先缩回去，想等情绪过去再说。',
        growth_suggestion: '提前约好冷静窗口，比临时消失更有安全感。',
      },
    },
    repairProtocol: {
    protocol_type: 'structured_repair',
    level: 'moderate',
    title: '先降温的缓和步骤',
    summary: '先停一下，再说一个点。',
    timing_hint: '先用文字铺垫，再约一个 10 分钟短通话。',
    active_plan_type: 'conflict_repair_plan',
    model_family: '亲健整理',
    clinical_disclaimer: '不替代法律、医疗或专业心理支持。',
    focus_tags: ['异地', '冲突缓和', '低刺激'],
    theory_basis: [],
    steps: [
      { sequence: 1, title: '先停 10-20 分钟', action: '先不继续追问，让情绪从顶点降下来。', why: '避免越说越僵。', duration_hint: '10-20 分钟' },
      { sequence: 2, title: '只说一个点', action: '先说刚刚最让你失落的一件事，不顺手翻出第二个问题。', why: '越聚焦，越容易听进去。', duration_hint: '2 分钟' },
      { sequence: 3, title: '先讲感受，再讲需求', action: '用“我刚刚有点失落，因为……”代替“你怎么又……”。', why: '对方更不容易先防御。', duration_hint: '2 分钟' },
      { sequence: 4, title: '约一个小动作', action: '最后只确认一个今晚就能做到的小调整。', why: '让缓和落到动作上。', duration_hint: '1 分钟' },
    ],
    do_not: ['不要继续翻旧账。', '不要逼对方立刻给出最终结论。', '不要在失控时做重大决定。'],
    success_signal: '对方愿意继续回应，并能确认一个小的下一步。',
    escalation_rule: '如果再次出现明显升级、羞辱或断联试探，请先停下，直接寻求人工支持。',
    evidence_summary: ['现在还在中度风险里。', '最近有过高风险发前检查。', '今晚适合低刺激沟通。'],
    limitation_note: '仅供沟通前参考。',
    safety_handoff: '如果出现威胁、羞辱或失控，请先求助。',
  },
  methodology: {
    system_name: '亲健整理方式第一版',
    model_family: '规则判断 + 反馈校准',
    measurement_model: ['每日记录与情绪/互动指标', '安排完成情况', '主观有用度与执行摩擦', '风险等级与健康分趋势'],
    decision_model: ['先看风险层级，再决定是否降温', '根据完成情况和反馈调整分支', '根据当前安排切换提醒和缓和建议'],
    active_modules: ['事件流', '画像快照', '反馈卡片', '当前安排', '冲突缓和建议', '双人安排'],
    current_focus: ['先降温', '再对齐理解', '最后落一个缓和动作'],
    disclaimer: '亲健参考关系心理学和行为科学做整理，不是医学诊断、临床治疗或正式心理测评工具。',
  },
  assessmentPack: {
    title: '关系体检',
    subtitle: '10 题体检。',
    latest_score: 72,
    change_summary: '比上一轮顺一点，继续按现在的节奏来。',
    generated_at: '2026-04-21T09:00:00+08:00',
    items: [
      { item_id: 'anchor-connection-1', track: 'core', dimension: 'connection', dimension_label: '连接与表达', prompt: '这段关系里，我们最近还能把真实想法说出来。', rotation_group: 'anchor', active: true, version: 'v1', options: [{ id: 'opt_0', label: '很不符合', score: 0 }, { id: 'opt_25', label: '不太符合', score: 25 }, { id: 'opt_50', label: '一半一半', score: 50 }, { id: 'opt_75', label: '比较符合', score: 75 }, { id: 'opt_100', label: '很符合', score: 100 }] },
      { item_id: 'anchor-connection-2', track: 'core', dimension: 'connection', dimension_label: '连接与表达', prompt: '最近沟通时，我们更像在说同一件事，而不是各说各的。', rotation_group: 'anchor', active: true, version: 'v1', options: [{ id: 'opt_0', label: '很不符合', score: 0 }, { id: 'opt_25', label: '不太符合', score: 25 }, { id: 'opt_50', label: '一半一半', score: 50 }, { id: 'opt_75', label: '比较符合', score: 75 }, { id: 'opt_100', label: '很符合', score: 100 }] },
      { item_id: 'anchor-trust-1', track: 'core', dimension: 'trust', dimension_label: '信任与安全', prompt: '最近我大多数时候都能感到被尊重和被认真对待。', rotation_group: 'anchor', active: true, version: 'v1', options: [{ id: 'opt_0', label: '很不符合', score: 0 }, { id: 'opt_25', label: '不太符合', score: 25 }, { id: 'opt_50', label: '一半一半', score: 50 }, { id: 'opt_75', label: '比较符合', score: 75 }, { id: 'opt_100', label: '很符合', score: 100 }] },
  { item_id: 'anchor-repair-1', track: 'core', dimension: 'repair', dimension_label: '缓和能力', prompt: '有摩擦的时候，我们最近更容易回到同一边。', rotation_group: 'anchor', active: true, version: 'v1', options: [{ id: 'opt_0', label: '很不符合', score: 0 }, { id: 'opt_25', label: '不太符合', score: 25 }, { id: 'opt_50', label: '一半一半', score: 50 }, { id: 'opt_75', label: '比较符合', score: 75 }, { id: 'opt_100', label: '很符合', score: 100 }] },
      { item_id: 'anchor-shared-future-1', track: 'core', dimension: 'shared_future', dimension_label: '共同愿景', prompt: '最近我们对这段关系接下来怎么走，仍然有基本共识。', rotation_group: 'anchor', active: true, version: 'v1', options: [{ id: 'opt_0', label: '很不符合', score: 0 }, { id: 'opt_25', label: '不太符合', score: 25 }, { id: 'opt_50', label: '一半一半', score: 50 }, { id: 'opt_75', label: '比较符合', score: 75 }, { id: 'opt_100', label: '很符合', score: 100 }] },
      { item_id: 'anchor-vitality-1', track: 'core', dimension: 'vitality', dimension_label: '关系活力', prompt: '最近和对方相处时，我还能感到一点轻松或愉快。', rotation_group: 'anchor', active: true, version: 'v1', options: [{ id: 'opt_0', label: '很不符合', score: 0 }, { id: 'opt_25', label: '不太符合', score: 25 }, { id: 'opt_50', label: '一半一半', score: 50 }, { id: 'opt_75', label: '比较符合', score: 75 }, { id: 'opt_100', label: '很符合', score: 100 }] },
      { item_id: 'rot-trust-1', track: 'rotation', dimension: 'trust', dimension_label: '信任与安全', prompt: '最近我不太需要反复确认自己在这段关系里的位置。', rotation_group: 'trust-a', active: true, version: 'v1', options: [{ id: 'opt_0', label: '很不符合', score: 0 }, { id: 'opt_25', label: '不太符合', score: 25 }, { id: 'opt_50', label: '一半一半', score: 50 }, { id: 'opt_75', label: '比较符合', score: 75 }, { id: 'opt_100', label: '很符合', score: 100 }] },
      { item_id: 'rot-repair-1', track: 'rotation', dimension: 'repair', dimension_label: '缓和能力', prompt: '最近不舒服的时候，我们更容易先把节奏放慢。', rotation_group: 'repair-a', active: true, version: 'v1', options: [{ id: 'opt_0', label: '很不符合', score: 0 }, { id: 'opt_25', label: '不太符合', score: 25 }, { id: 'opt_50', label: '一半一半', score: 50 }, { id: 'opt_75', label: '比较符合', score: 75 }, { id: 'opt_100', label: '很符合', score: 100 }] },
      { item_id: 'rot-shared-future-1', track: 'rotation', dimension: 'shared_future', dimension_label: '共同愿景', prompt: '最近我们对下一步想保留什么关系节奏，越来越清楚。', rotation_group: 'future-a', active: true, version: 'v1', options: [{ id: 'opt_0', label: '很不符合', score: 0 }, { id: 'opt_25', label: '不太符合', score: 25 }, { id: 'opt_50', label: '一半一半', score: 50 }, { id: 'opt_75', label: '比较符合', score: 75 }, { id: 'opt_100', label: '很符合', score: 100 }] },
      { item_id: 'rot-vitality-2', track: 'rotation', dimension: 'vitality', dimension_label: '关系活力', prompt: '最近我们相处时，偶尔还能自然地笑出来。', rotation_group: 'vitality-b', active: true, version: 'v1', options: [{ id: 'opt_0', label: '很不符合', score: 0 }, { id: 'opt_25', label: '不太符合', score: 25 }, { id: 'opt_50', label: '一半一半', score: 50 }, { id: 'opt_75', label: '比较符合', score: 75 }, { id: 'opt_100', label: '很符合', score: 100 }] },
    ],
  },
  assessmentLatest: {
    event_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    submitted_at: '2026-04-14T21:00:00',
    total_score: 72,
    scope: 'pair',
    change_summary: '比上一轮顺一点，继续按现在的节奏来。',
    dimension_scores: [
      { id: 'connection', label: '连接与表达', score: 75, status: 'strong' },
      { id: 'trust', label: '信任与安全', score: 62, status: 'watch' },
      { id: 'repair', label: '缓和能力', score: 58, status: 'watch' },
      { id: 'shared_future', label: '共同愿景', score: 76, status: 'strong' },
      { id: 'vitality', label: '关系活力', score: 70, status: 'watch' },
    ],
  },
  assessmentTrend: {
    latest_score: 72,
    change_summary: '比上一轮顺一点，继续按现在的节奏来。',
    dimension_scores: [
      { id: 'connection', label: '连接与表达', score: 75, status: 'strong' },
      { id: 'trust', label: '信任与安全', score: 62, status: 'watch' },
      { id: 'repair', label: '缓和能力', score: 58, status: 'watch' },
      { id: 'shared_future', label: '共同愿景', score: 76, status: 'strong' },
      { id: 'vitality', label: '关系活力', score: 70, status: 'watch' },
    ],
    trend_points: [
      { event_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', submitted_at: '2026-03-24T21:00:00', total_score: 66, scope: 'pair', change_summary: '第一份体检，先留下一个起点。', dimension_scores: [] },
      { event_id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc', submitted_at: '2026-03-31T21:00:00', total_score: 68, scope: 'pair', change_summary: '比上一轮顺一点，继续按现在的节奏来。', dimension_scores: [] },
      { event_id: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd', submitted_at: '2026-04-07T21:00:00', total_score: 70, scope: 'pair', change_summary: '比上一轮顺一点，继续按现在的节奏来。', dimension_scores: [] },
      { event_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', submitted_at: '2026-04-14T21:00:00', total_score: 72, scope: 'pair', change_summary: '比上一轮顺一点，继续按现在的节奏来。', dimension_scores: [] },
    ],
  },
  reportHistory: [
    { id: '66666666-6666-4666-8666-666666666664', report_type: 'daily', status: 'completed', created_at: '2026-03-19T22:05:00', health_score: 71 },
    { id: '66666666-6666-4666-8666-666666666665', report_type: 'daily', status: 'completed', created_at: '2026-03-20T22:06:00', health_score: 75 },
    { id: '66666666-6666-4666-8666-666666666666', report_type: 'daily', status: 'completed', created_at: '2026-03-21T22:10:00', health_score: 78 },
  ],
  timelineArchive: [
    {
      id: 'archive-demo-1',
      item_type: 'record',
      occurred_at: '2026-03-21T20:40:00',
      local_date: '2026-03-21',
      title: '委屈的一次记录',
      summary: '这天更像在记录委屈，同时也带着期待。也附带了一张图片，画面里更像双方在缓和误会。',
      tags: ['委屈', '期待', '图片线索'],
      visibility: 'owner_only',
      has_raw_content: true,
      has_image_original: true,
      has_voice_original: false,
      raw_retention_until: '2026-03-28T20:40:00',
      raw_deleted_at: null,
      download_available: true,
      record: {
      content: '我其实还是有点委屈，但也想把这次误会说开。',
        mood_tags: ['委屈', '期待'],
        sentiment_score: 6.8,
        mood_score: 6,
        interaction_freq: 4,
        interaction_initiative: 'me',
        deep_conversation: true,
        task_completed: false,
        image: {
          access_url: null,
          available: true,
          analysis: {
            scene_summary: '一张聊天截图，双方在尝试把误会说开。',
            mood: '温柔里带着一点脆弱',
          },
        },
        voice: {
          access_url: null,
          available: false,
          duration_seconds: null,
          silence_ratio: null,
        },
        archive_insight: {
          text_emotion: {
            primary_mood: '委屈',
            secondary_moods: ['期待'],
            reason: '识别到主情绪更像委屈，同时也有期待。',
          },
        },
        client_context_preview: {
          intent: 'reflection',
          risk_level: 'watch',
          upload_policy: 'full',
          source_type: 'mixed',
        },
      },
    },
    {
      id: 'archive-demo-2',
      item_type: 'partner_record_placeholder',
      occurred_at: '2026-03-21T21:00:00',
      local_date: '2026-03-21',
      title: '对方在这天也留下了一条记录',
      summary: '对方也在这天记录了一个重要时刻，内容更像在放低防御。',
      tags: ['缓和', '平稳'],
      visibility: 'shared_summary',
      locked_reason: '原文和原媒体默认仅记录者本人可见。',
      has_raw_content: false,
      has_image_original: false,
      has_voice_original: false,
      raw_retention_until: '2026-03-28T21:00:00',
      raw_deleted_at: null,
      download_available: false,
    },
    {
      id: 'archive-demo-3',
      item_type: 'report',
      occurred_at: '2026-03-21T22:10:00',
      local_date: '2026-03-21',
      title: '每日报告',
      summary: '你们不是没有连接，只是每次想靠近时，容易先被压力打断。',
      tags: ['报告', '每日报告'],
      visibility: 'shared_report',
      has_raw_content: false,
      has_image_original: false,
      has_voice_original: false,
      raw_retention_until: null,
      raw_deleted_at: null,
      download_available: true,
      report: {
        report_type: 'daily',
        status: 'completed',
        health_score: 78,
        report_date: '2026-03-21',
        summary: '你们不是没有连接，只是每次想靠近时，容易先被压力打断。',
        recommendations: ['今天做一个简单的缓和动作，不求一次解决所有问题。', '把复盘控制在 10 分钟内。'],
        content: {
          insight: '你们不是没有连接，只是每次想靠近时，容易先被压力打断。',
        },
      },
    },
  ],
  timelineEvents: [
    {
      id: 'timeline-demo-1',
      title: '第一次把误会说完整',
      description: '你先记录原话，她补充当时没有说出口的担心。',
      timestamp: '2026-03-19T21:10:00',
      tags: ['原话', '缓和'],
    },
    {
      id: 'timeline-demo-2',
      title: '朋友关系里重新约了一次饭',
      description: '周宁没有退出，只是最近精力低，你们把期待改成低压力见面。',
      timestamp: '2026-03-20T19:30:00',
      tags: ['朋友', '同步期待'],
    },
    {
      id: 'timeline-demo-3',
      title: '陈一和顾遥建立了新的朋友空间',
      description: '这段关系先从轻松的小约定开始，不急着被放进任何固定标签里。',
      timestamp: '2026-03-21T20:40:00',
      tags: ['朋友', '新空间'],
    },
  ],
  milestones: [
    {
      id: 'milestone-demo-1',
      type: 'anniversary',
      title: '第一次认真复盘',
      date: '2026-02-14',
    },
    {
      id: 'milestone-demo-2',
      type: 'friendship_day',
      title: '陈一和周宁重新约上饭',
      date: '2026-03-16',
    },
    {
      id: 'milestone-demo-3',
      type: 'custom',
      title: '陈一和顾遥第一次一起完成记录',
      date: '2026-03-21',
    },
  ],
  longDistance: {
    health: {
      health_index: 82,
      status: 'stable',
    },
    activities: [
      { id: 'ld-demo-1', activity_type: 'movie', status: 'completed' },
      { id: 'ld-demo-2', activity_type: 'chat', status: 'completed' },
      { id: 'ld-demo-3', activity_type: 'meal', status: 'pending' },
    ],
  },
}

export function cloneDemo(value = demoFixture) {
  return JSON.parse(JSON.stringify(value))
}

const DEMO_ASSESSMENT_PROFILE_COPY = {
  couple: {
    title: '关系体检',
    subtitle: '10 题，看这段关系最该照顾哪里。',
  },
  solo: {
    title: '自我诊断',
    subtitle: '10 题，看你最近最容易卡在哪里。',
  },
  friend: {
    title: '友情体检',
    subtitle: '10 题，看这段友情最该照顾哪里。',
  },
  spouse: {
    title: '婚姻体检',
    subtitle: '10 题，看这段婚姻最该照顾哪里。',
  },
  long_distance: {
    title: '异地关系体检',
    subtitle: '10 题，看异地里最该照顾哪里。',
  },
}

const DEMO_ASSESSMENT_PROMPT_VARIANTS = {
  solo: {
    'anchor-connection-1': '过去一周里，我还能把真正介意的事说出来，不需要一直憋着。',
    'anchor-connection-2': '最近一次重要沟通里，我大致能说清自己到底在介意什么。',
    'anchor-trust-1': '最近大多数时候，我不太需要靠猜测或反复确认，来证明自己在关系里还有位置。',
    'anchor-repair-1': '有摩擦时，我最近至少能先停下来，不把局面越顶越高。',
    'anchor-shared-future-1': '最近我对自己想保留什么样的关系状态，仍然有一点基本认识。',
    'anchor-vitality-1': '最近在关系里，除了压力，我还能感到一点轻松或舒服。',
    'rot-trust-1': '最近我不太需要靠试探、冷一下或反复确认，来判断别人还在不在乎我。',
    'rot-repair-1': '最近有摩擦时，我更能先停 10 分钟，而不是一直追着把话说死。',
    'rot-shared-future-1': '最近我对“这段关系值不值得继续投入”这件事，想法比以前更清楚一点。',
    'rot-vitality-2': '最近在关系里，我偶尔还能自然笑出来，而不只是处理问题。',
  },
  friend: {
    'anchor-connection-1': '过去一周里，这段友情里真正介意的事，我们还能说出来，不需要一直憋着。',
    'anchor-connection-2': '最近一次认真聊天里，我们大致能听懂对方到底在介意什么。',
    'anchor-trust-1': '最近我大多数时候都不用靠猜，能知道自己在这段友情里的位置。',
    'anchor-repair-1': '有别扭时，我们最近至少有一方能先停下来，不把气氛越顶越僵。',
    'anchor-shared-future-1': '最近我们对这段友情接下来怎么相处，仍然有基本共识。',
    'anchor-vitality-1': '最近和这个朋友相处时，除了压力，我还能感到一点轻松或舒服。',
  },
  spouse: {
    'anchor-connection-1': '过去一周里，这段婚姻里真正介意的事，我们还能说出来，不需要一直憋着。',
    'anchor-connection-2': '最近一次重要沟通里，我们大致能听懂对方到底在介意什么，而不是只剩情绪。',
    'anchor-trust-1': '最近我大多数时候都不用靠猜，能知道自己在这段婚姻里的位置。',
    'anchor-repair-1': '有摩擦时，我们最近至少有一方能先停下来，不把家里的气氛越顶越高。',
    'anchor-shared-future-1': '最近我们对这段婚姻接下来怎么走，仍然有基本共识。',
    'anchor-vitality-1': '最近和对方待在一起时，除了现实压力，我还能感到一点轻松或舒服。',
  },
  long_distance: {
    'anchor-connection-1': '过去一周里，隔着距离时真正介意的事，我们还能说出来，不需要一直憋着。',
    'anchor-connection-2': '最近一次重要联系里，我们大致能听懂对方到底在介意什么。',
    'anchor-trust-1': '最近我大多数时候都不用靠猜，能知道自己在这段异地关系里的位置。',
    'anchor-repair-1': '有摩擦时，我们最近至少有一方能先停下来，不把隔着距离的误会越顶越高。',
    'anchor-shared-future-1': '最近我们对这段异地关系接下来怎么走，仍然有基本共识。',
    'anchor-vitality-1': '最近隔着距离联系时，除了压力，我还能感到一点轻松或被陪到。',
  },
}

function demoAssessmentProfileForPair(pair = null) {
  if (pair === 'solo') return 'solo'
  if (!pair) return 'couple'
  if (pair.is_long_distance && ['couple', 'spouse'].includes(pair.type)) return 'long_distance'
  if (['friend', 'bestfriend'].includes(pair.type)) return 'friend'
  if (['spouse', 'parent'].includes(pair.type)) return 'spouse'
  return 'couple'
}

export function buildDemoAssessmentPack(pair = null) {
  const pack = cloneDemo(demoFixture.assessmentPack)
  const profile = demoAssessmentProfileForPair(pair)
  const profileCopy = DEMO_ASSESSMENT_PROFILE_COPY[profile] || DEMO_ASSESSMENT_PROFILE_COPY.couple
  const promptVariants = DEMO_ASSESSMENT_PROMPT_VARIANTS[profile] || {}

  pack.title = profileCopy.title
  pack.subtitle = profileCopy.subtitle
  pack.items = (pack.items || []).map((item) => ({
    ...item,
    prompt: promptVariants[item.item_id] || item.prompt,
  }))

  return pack
}
