export const DEMO_TOKEN = 'demo-mode'

export const demoFixture = {
  me: {
    id: '11111111-1111-4111-8111-111111111111',
    email: 'demo@qinjian.local',
    nickname: '陈一',
    ai_assist_enabled: true,
    privacy_mode: 'cloud',
    preferred_entry: 'daily',
    preferred_language: 'zh',
    tone_preference: 'gentle',
    response_length: 'medium',
    created_at: '2026-02-02T09:00:00',
  },
  currentPairId: '22222222-2222-4222-8222-222222222222',
  pairs: [
    {
      id: '22222222-2222-4222-8222-222222222222',
      user_a_id: '11111111-1111-4111-8111-111111111111',
      user_b_id: '33333333-3333-4333-8333-333333333333',
      type: 'couple',
      status: 'active',
      invite_code: 'A3H7K8M9Q2',
      partner_nickname: '林夏',
      partner_email: 'linxia@demo.local',
      custom_partner_nickname: '林夏',
      created_at: '2026-02-14T20:00:00',
    },
    {
      id: '77777777-7777-4777-8777-777777777777',
      user_a_id: '11111111-1111-4111-8111-111111111111',
      user_b_id: '88888888-8888-4888-8888-888888888888',
      type: 'friend',
      status: 'active',
      invite_code: 'B4J8L9N2P3',
      partner_nickname: '周宁',
      partner_email: 'zhouning@demo.local',
      custom_partner_nickname: '周宁',
      created_at: '2026-03-08T18:20:00',
    },
    {
      id: '99999999-9999-4999-8999-999999999999',
      user_a_id: '11111111-1111-4111-8111-111111111111',
      user_b_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
      type: 'friend',
      status: 'active',
      invite_code: 'C5K9M2Q4R7',
      partner_nickname: '顾遥',
      partner_email: 'guyao@demo.local',
      custom_partner_nickname: '顾遥',
      created_at: '2026-03-16T15:00:00',
    },
  ],
  notifications: [
    {
      id: '44444444-4444-4444-8444-444444444444',
      type: 'system',
      content: '样例演示已启用，可以放心试用主要功能。',
      is_read: false,
      created_at: '2026-03-21T09:30:00',
    },
  ],
  todayStatus: {
    pair_id: '22222222-2222-4222-8222-222222222222',
    my_done: true,
    partner_done: true,
    both_done: true,
    has_report: true,
  },
  tree: {
    name: '关系树',
    level: 'tree',
    level_name: '话说开了',
    stage_label: '话说开了',
    stage_title: '原来别着的话，开始能说出来了',
    stage_explanation: '你们最近没那么僵着了，有些以前说不出口的话，现在也能慢慢聊开。',
    growth_points: 148,
    progress_percent: 57,
    next_level_at: 260,
    last_watered: '2026-04-12',
    can_water: true,
    water_bonus: 18,
    decay_per_day: 7,
    decay_grace_days: 0,
    energy_bubbles: [
      { label: '记录', value: '+12' },
      { label: '共情', value: '+8' },
      { label: '修复', value: '+16' },
    ],
    leaves: [
      { label: '原话', value: '12 条', note: '这周被完整留下来的关键句' },
      { label: '修复', value: '5 次', note: '从冷下来到重新接上的节点' },
      { label: '共同记忆', value: '18 个', note: '不是问题，也被保存下来的片段' },
    ],
  },
  relationshipSpaces: [
    {
      id: 'couple-repair',
      pair_id: '22222222-2222-4222-8222-222222222222',
      type: '情侣',
      title: '陈一和林夏',
      people: ['陈一', '林夏'],
      tree_stage: '小树',
      status: '今天适合低压力修复',
      prompt: '先把“你没懂我”这句话留住，再约一个 10 分钟电话。',
      signal: 78,
      moments: ['昨天因为回复慢误会', '今天双方都愿意补一句解释', '下一步只确认一个小调整'],
    },
    {
      id: 'friend-sync',
      pair_id: '77777777-7777-4777-8777-777777777777',
      type: '朋友',
      title: '陈一和周宁',
      people: ['陈一', '周宁'],
      tree_stage: '新芽',
      status: '友情里需要同步期待',
      prompt: '适合说清楚“我不是不想见你，只是最近恢复很慢”。',
      signal: 84,
      moments: ['两周没约上饭', '一方担心被疏远', '可以用轻一点的方式重新约时间'],
    },
    {
      id: 'friend-boundary',
      pair_id: '99999999-9999-4999-8999-999999999999',
      type: '朋友',
      title: '陈一和顾遥',
      people: ['陈一', '顾遥'],
      tree_stage: '种子',
      status: '新关系先从低压力陪伴开始',
      prompt: '先约一件轻松的小事，不急着把关系定义得太满。',
      signal: 69,
      moments: ['刚开始一起玩', '双方还在找舒服的节奏', '适合保留一个小约定'],
    },
  ],
  relationshipMetrics: {
    '22222222-2222-4222-8222-222222222222': {
      score: 78,
      trend: 'up',
      summary: '今天双方都愿意补一句解释，关系在慢慢回暖。',
      nextAction: '先约一个 10 分钟电话，把误会说清楚。',
    },
    '77777777-7777-4777-8777-777777777777': {
      score: 84,
      trend: 'flat',
      summary: '友情整体稳定，但最近见面频率下降了一点。',
      nextAction: '发一个轻松邀约，先把见面重新约起来。',
    },
    '99999999-9999-4999-8999-999999999999': {
      score: 69,
      trend: 'up',
      summary: '这段新关系正在建立节奏，最近有变近的趋势。',
      nextAction: '先保留一个小约定，不急着定义关系。',
    },
  },
  crisis: {
    crisis_level: 'moderate',
    intervention: {
      title: '先降温，再做个简单的修复动作。',
      description: '当前阶段更适合低压力修复，不适合一次性解决所有问题。',
    },
  },
  communityTips: [
    {
      id: 'tip-demo-1',
      title: '先复述，再回应',
      content: '对方表达委屈时，先复述你听到的重点，再补充自己的解释。',
    },
    {
      id: 'tip-demo-2',
      title: '一次只说一个点',
      content: '冲突刚结束时，不要把所有旧问题都拿出来，更容易让对话继续。',
    },
  ],
  tasks: {
    adaptive_strategy: {
      reason: '建议先稳住情绪，再安排一个小行动。',
      copy_mode: 'gentle',
      copy_feedback_count: 3,
    },
    tasks: [
      {
        id: 'task-demo-1',
        title: '发一条简单的说明',
        description: '先说感受，再说一个具体需求，不急着把所有问题说完。',
        category: 'repair',
        status: 'pending',
        copy_mode: 'gentle',
        copy_mode_source: 'category',
      },
      {
        id: 'task-demo-2',
        title: '今晚打个短电话',
        description: '目标是确认彼此还在同一频道，而不是立刻讨论所有问题。',
        category: 'connection',
        status: 'pending',
      },
      {
        id: 'task-demo-3',
        title: '记录这个方法是否有效',
        description: '明天回来补充反馈，帮系统更好地给你建议。',
        category: 'reflection',
        status: 'completed',
        feedback: {
          usefulness_score: 4,
          note: '这样做之后，对方没有继续升级。',
        },
        needs_feedback: false,
      },
    ],
  },
  streak: { streak: 6 },
  latestReport: {
    id: '66666666-6666-4666-8666-666666666666',
    pair_id: '22222222-2222-4222-8222-222222222222',
    report_type: 'daily',
    status: 'completed',
    created_at: '2026-03-21T22:10:00',
    health_score: 78,
    summary: '你们并不是没有连接，而是每次想靠近时，都更容易先被压力接住。',
    key_insights: [
      '这周双方都没有完全退出关系，仍愿意继续回应。',
      '共同愿景和长期目标感仍然稳定。',
      '高压力表达仍会触发对方的防御。',
    ],
    recommendations: [
      '今天做一个简单的修复动作，不求一次解决所有问题。',
      '用"我刚刚有点失落，因为……"代替"你怎么又……"。',
      '把复盘控制在10分钟内，只确认一个今晚能做到的小调整。',
    ],
  },
  narrativeAlignment: {
    event_id: '99999999-9999-4999-8999-999999999999',
    pair_id: '22222222-2222-4222-8222-222222222222',
    checkin_date: '2026-03-21',
    user_a_label: '陈一',
    user_b_label: '林夏',
    alignment_score: 71,
    shared_story: '你们都在乎这段关系，只是最近一个人在努力确认“我还重要吗”，另一个人在努力证明“我不是不在乎，只是太累了”。',
    view_a_summary: '你更在意被及时回应，因为延迟会被你接成自己不被在乎。',
    view_b_summary: '对方更像是在疲惫和压力里撤退，并不是真的想退出关系。',
    misread_risk: '最容易错位的点是：你的追问在对方那里会先被听成压力，而不是需要靠近。',
    divergence_points: ['你以为自己是在确认连接，对方感受到的是再次被要求交代。', '对方以为沉默是在避免升级，你感受到的却是被抛下。'],
    bridge_actions: ['先用一句低刺激感受表达开头，不要直接追问。', '先确认对方是否有 10 分钟空档，再进入主题。', '只对齐一个误解点，不要顺手扩展到所有旧问题。'],
    suggested_opening: '我不是想和你算账，我只是想把刚刚那点失落说清楚，看看我们能不能找到一个更不累的沟通方式。',
    coach_note: '这次先对齐“彼此其实都没想退出”这一点，会比直接争谁更委屈更有帮助。',
    algorithm_version: 'relationship_judgement_v2',
    confidence: 0.74,
    decision_trace: { algorithm_version: 'relationship_judgement_v2', layer: 'alignment' },
    focus_labels: ['回应节奏', '缓冲空间'],
    risk_score: 0.29,
    baseline_delta: 17,
    fallback_reason: null,
    shadow_result: null,
    feedback_status: 'pending_feedback',
    reaction_shift: '林夏：这次更像在退开或关掉沟通。',
    deviation_reasons: ['陈一这次说得比平时更长，容易让对方先感到压力。', '林夏这次更像在退开，可能不是不在乎，而是需要先降温。'],
    history_sufficiency: 'limited',
    current_risk_level: 'moderate',
    active_plan_type: 'conflict_repair_plan',
    generated_at: '2026-03-21T22:15:00',
  },
  messageSimulation: {
    event_id: '88888888-8888-4888-8888-888888888888',
    draft: '你今天怎么又这么晚才回我，我真的很烦。',
    partner_view: '对方很可能先听成“你又做错了”，而不是“我现在有点受伤”。',
    likely_impact: '如果直接发送，接下来更可能进入解释、防御或沉默，而不是修复。',
    risk_level: 'high',
    risk_reason: '这句话把情绪和指责绑在一起，对方更容易先感到压力，而不是看见你的真实需求。',
    safer_rewrite: '我刚刚有点失落，因为等了很久都没收到你的消息。你忙的时候如果能先告诉我一声，我会安心很多。',
    suggested_tone: '低刺激',
    conversation_goal: '先让对方接住你的感受',
    do_list: ['先说自己的感受，再说一个具体需求。', '一次只说一个点，不要顺手翻旧账。', '把目标放在重新建立沟通窗口，而不是马上讲赢。'],
    avoid_list: ['避免“你怎么又”这类绝对化开头。', '不要把等待感直接写成指责。', '不要在情绪顶点继续加长句。'],
    algorithm_version: 'relationship_judgement_v2',
    confidence: 0.78,
    decision_trace: { algorithm_version: 'relationship_judgement_v2', layer: 'message_simulation' },
    focus_labels: ['回应节奏', '压力感'],
    risk_score: 2.3,
    baseline_delta: 1.3,
    fallback_reason: null,
    shadow_result: null,
    feedback_status: 'pending_feedback',
    baseline_match: 'strong_deviation',
    deviation_score: 0.78,
    deviation_reasons: ['本次语气更强烈，和平时表达习惯不同', '这次风险和刺激性明显高于平时'],
    reaction_shift: '这次更像在防御或顶回去。',
    evidence_summary: ['最近已有 2 次高风险消息预演。', '当前仍处在中度风险区间。', '当前策略要求优先降低表达刺激性。'],
    limitation_note: '预演只基于最近关系画像和事件流，不等于对对方真实反应的绝对预测。',
    safety_handoff: '如果这次沟通已经多次升级，请先不要发送，改为暂停、降温，必要时转向人工支持。',
  },
  repairProtocol: {
    protocol_type: 'structured_repair',
    level: 'moderate',
    title: '中度冲突修复方案',
    summary: '当前更适合先降温、再用结构化表达回到同一频道，而不是继续硬谈到底。',
    timing_hint: '先用文字铺垫，再约一个 10 分钟短通话。',
    active_plan_type: 'conflict_repair_plan',
    model_family: '安全优先的规则引擎',
    clinical_disclaimer: '修复方案用于一般沟通冲突，不替代法律、医疗或专业心理支持。',
    focus_tags: ['异地', '冲突修复', '低刺激'],
    theory_basis: [],
    steps: [
      { sequence: 1, title: '先停 10-20 分钟', action: '先不继续追问，让情绪从顶点降下来。', why: '避免把修复再次打成争执。', duration_hint: '10-20 分钟' },
      { sequence: 2, title: '只说一个点', action: '先说刚刚最让你失落的一件事，不顺手翻出第二个问题。', why: '越聚焦，对方越容易接住。', duration_hint: '2 分钟' },
      { sequence: 3, title: '先讲感受，再讲需求', action: '用“我刚刚有点失落，因为……”代替“你怎么又……”。', why: '能显著降低对方的防御感。', duration_hint: '2 分钟' },
      { sequence: 4, title: '约一个小动作', action: '最后只确认一个今晚就能做到的小调整。', why: '把修复落成动作，而不是只停在道理。', duration_hint: '1 分钟' },
    ],
    do_not: ['不要继续翻旧账。', '不要逼对方立刻给出最终结论。', '不要在失控时做重大决定。'],
    success_signal: '对方愿意继续回应，并能确认一个小的下一步。',
    escalation_rule: '如果再次出现明显升级、羞辱或断联试探，请暂停产品内修复，直接寻求人工支持。',
    evidence_summary: ['当前处在中度风险区间，修复节奏需要以止损优先。', '最近仍有高风险消息预演，所以方案保持低刺激结构。', '当前仍有一条冲突修复计划在执行。'],
    limitation_note: '修复方案基于最近风险等级、关系画像和当前计划生成，它帮助双方降温和重建沟通，不替代专业判断。',
    safety_handoff: '如果已经出现持续升级、威胁、羞辱、肢体伤害风险或明显失控，请停止继续推进对话，转向可信任的人、专业咨询或当地紧急支持。',
  },
  methodology: {
    system_name: '关系行为干预系统第一版',
    model_family: '规则引擎 + 反馈闭环',
    measurement_model: ['每日打卡与情绪/互动指标', '关系任务完成率', '主观有用度与执行摩擦', '风险等级与健康分趋势'],
    decision_model: ['先做风险分层，再决定是否降温', '根据完成率和反馈切剧本分支', '根据计划类型切换任务与修复策略'],
    active_modules: ['事件流', '画像快照', '干预评分卡', '剧本运行态', '冲突修复方案', '双人任务调度'],
    current_focus: ['先降温', '再对齐理解', '最后落修复动作'],
    disclaimer: '当前系统是基于关系心理学和行为科学启发的工程化决策系统，不是医学诊断、临床治疗或正式心理测评工具。',
  },
  reportHistory: [
    { id: '66666666-6666-4666-8666-666666666664', report_type: 'daily', status: 'completed', created_at: '2026-03-19T22:05:00', health_score: 71 },
    { id: '66666666-6666-4666-8666-666666666665', report_type: 'daily', status: 'completed', created_at: '2026-03-20T22:06:00', health_score: 75 },
    { id: '66666666-6666-4666-8666-666666666666', report_type: 'daily', status: 'completed', created_at: '2026-03-21T22:10:00', health_score: 78 },
  ],
  timelineEvents: [
    {
      id: 'timeline-demo-1',
      title: '第一次把误会说完整',
      description: '你先记录原话，她补充当时没有说出口的担心。',
      timestamp: '2026-03-19T21:10:00',
      tags: ['原话', '修复'],
    },
    {
      id: 'timeline-demo-2',
      title: '朋友关系里重新约了一次饭',
      description: '周宁没有退出，只是最近精力低，你们把期待改成低压力见面。',
      timestamp: '2026-03-20T19:30:00',
      tags: ['朋友', '同步期待'],
    },
    {
      id: 'timeline-demo-3',
      title: '陈一和顾遥建立了新的朋友空间',
      description: '这段关系先从轻松的小约定开始，不急着被放进任何固定标签里。',
      timestamp: '2026-03-21T20:40:00',
      tags: ['朋友', '新空间'],
    },
  ],
  milestones: [
    {
      id: 'milestone-demo-1',
      type: 'anniversary',
      title: '第一次认真复盘',
      date: '2026-02-14',
    },
    {
      id: 'milestone-demo-2',
      type: 'friendship_day',
      title: '陈一和周宁重新约上饭',
      date: '2026-03-16',
    },
    {
      id: 'milestone-demo-3',
      type: 'custom',
      title: '陈一和顾遥第一次一起完成记录',
      date: '2026-03-21',
    },
  ],
  longDistance: {
    health: {
      health_index: 82,
      status: 'stable',
    },
    activities: [
      { id: 'ld-demo-1', activity_type: 'movie', status: 'completed' },
      { id: 'ld-demo-2', activity_type: 'chat', status: 'completed' },
      { id: 'ld-demo-3', activity_type: 'meal', status: 'pending' },
    ],
  },
}

export function cloneDemo(value = demoFixture) {
  return JSON.parse(JSON.stringify(value))
}
